-- 그룹웨어 전체 스키마
-- 출처: ERD_설계서.md 5장 (내용이 바뀌면 그쪽을 먼저 고치고 여기 동기화할 것)
-- 실행 순서 중요: FK가 참조하는 테이블이 먼저 생성돼야 함

-- 데이터베이스 생성 및 선택
CREATE DATABASE groupware;
USE groupware;

-- ① DEPARTMENT — 다른 테이블이 참조하므로 가장 먼저 생성
CREATE TABLE DEPARTMENT (
    DEPT_ID   INT         AUTO_INCREMENT,
    DEPT_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPT_ID),
    CONSTRAINT UQ_DEPT_NAME  UNIQUE      (DEPT_NAME)
);

-- ② POSITION — 다른 테이블이 참조하므로 가장 먼저 생성
-- POSITION은 MySQL 예약어(POSITION() 함수와 이름이 겹침)라서 백틱으로 감싸야 함
CREATE TABLE `POSITION` (
    POSITION_ID   INT         AUTO_INCREMENT,
    POSITION_NAME VARCHAR(20) NOT NULL,
    POSITION_RANK INT         NOT NULL,   -- 1=부서장 … 5=사원
    CONSTRAINT PK_POSITION      PRIMARY KEY (POSITION_ID),
    CONSTRAINT UQ_POSITION_NAME UNIQUE      (POSITION_NAME)
);

-- ③ EMPLOYEE — DEPARTMENT, POSITION 참조
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID    INT          AUTO_INCREMENT,
    EMPLOYEE_NO    VARCHAR(20)  NOT NULL,               -- 사번(로그인 ID 겸용)
    EMPLOYEE_PWD   VARCHAR(300) NOT NULL,
    EMPLOYEE_NAME  VARCHAR(50)  NOT NULL,
    DEPT_ID        INT          NULL,        -- 관리자(ADMIN)는 NULL 허용
    POSITION_ID    INT          NULL,        -- 관리자(ADMIN)는 NULL 허용
    EMPLOYEE_ROLE  VARCHAR(10)  NOT NULL DEFAULT 'EMPLOYEE',  -- EMPLOYEE / ADMIN
    EMPLOYEE_PHONE VARCHAR(20)  NULL,
    EMPLOYEE_EMAIL VARCHAR(200) NULL,
    PROFILE_IMG    VARCHAR(500) NULL,
    EMPLOYEE_STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',    -- ACTIVE / SUSPENDED
    HIRE_DATE      DATE         NOT NULL,
    CREATED_AT     DATETIME     NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_EMPLOYEE         PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT UQ_EMPLOYEE_NO      UNIQUE      (EMPLOYEE_NO),
    CONSTRAINT FK_EMPLOYEE_DEPT    FOREIGN KEY (DEPT_ID)
                                   REFERENCES  DEPARTMENT(DEPT_ID),
    CONSTRAINT FK_EMPLOYEE_POSITION FOREIGN KEY (POSITION_ID)
                                   REFERENCES  `POSITION`(POSITION_ID),
    -- MySQL 8.0.16 미만에서는 아래 CHECK가 무시되므로, 서비스 계층에서도
    -- 동일 규칙(일반 직원 등록 시 부서·직급 필수)을 반드시 함께 검증할 것
    CONSTRAINT CK_EMPLOYEE_DEPT_POSITION CHECK (
        EMPLOYEE_ROLE = 'ADMIN' OR (DEPT_ID IS NOT NULL AND POSITION_ID IS NOT NULL)
    )
);

-- ④ ATTENDANCE — EMPLOYEE 참조
CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID     INT         AUTO_INCREMENT,
    EMPLOYEE_ID       INT         NOT NULL,
    WORK_DATE         DATE        NOT NULL,
    CHECK_IN_TIME     TIME        NULL,
    CHECK_OUT_TIME    TIME        NULL,
    ATTENDANCE_STATUS VARCHAR(10) NOT NULL,   -- NORMAL / LATE / LEAVE
    CONSTRAINT PK_ATTENDANCE       PRIMARY KEY (ATTENDANCE_ID),
    CONSTRAINT FK_ATTENDANCE_EMP   FOREIGN KEY (EMPLOYEE_ID)
                                   REFERENCES  EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT UQ_ATTENDANCE_DAY   UNIQUE      (EMPLOYEE_ID, WORK_DATE)
);

-- ⑤ NOTICE — EMPLOYEE 참조
CREATE TABLE NOTICE (
    NOTICE_ID      INT          AUTO_INCREMENT,
    WRITER_ID      INT          NOT NULL,
    NOTICE_TITLE   VARCHAR(200) NOT NULL,
    NOTICE_CONTENT TEXT         NOT NULL,
    IS_PINNED      TINYINT(1)   NOT NULL DEFAULT 0,
    VIEW_COUNT     INT          NOT NULL DEFAULT 0,
    CREATED_AT     DATETIME     NOT NULL DEFAULT NOW(),
    UPDATED_AT     DATETIME     NULL,
    CONSTRAINT PK_NOTICE        PRIMARY KEY (NOTICE_ID),
    CONSTRAINT FK_NOTICE_WRITER FOREIGN KEY (WRITER_ID)
                                REFERENCES  EMPLOYEE(EMPLOYEE_ID)
);

-- ⑥ CALENDAR_EVENT — EMPLOYEE 참조
CREATE TABLE CALENDAR_EVENT (
    EVENT_ID       INT          AUTO_INCREMENT,
    EMPLOYEE_ID    INT          NOT NULL,
    EVENT_TITLE    VARCHAR(200) NOT NULL,
    START_DATE     DATE         NOT NULL,
    END_DATE       DATE         NOT NULL,   -- 하루짜리 일정은 START_DATE와 동일
    EVENT_CATEGORY VARCHAR(10)  NOT NULL,   -- PERSONAL / TEAM / COMPANY
    CREATED_AT     DATETIME     NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_CALENDAR_EVENT PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_EVENT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
                                 REFERENCES  EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT CK_EVENT_DATE_RANGE CHECK (END_DATE >= START_DATE)
);

-- ⑦ REPOSITORY — DEPARTMENT 참조
CREATE TABLE REPOSITORY (
    REPO_ID    INT         AUTO_INCREMENT,
    REPO_NAME  VARCHAR(50) NOT NULL,
    DEPT_ID    INT         NULL,        -- NULL = 전사 공용
    CREATED_AT DATETIME    NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_REPOSITORY   PRIMARY KEY (REPO_ID),
    CONSTRAINT FK_REPOSITORY_DEPT FOREIGN KEY (DEPT_ID)
                               REFERENCES  DEPARTMENT(DEPT_ID)
);

-- ⑧ ARCHIVE — REPOSITORY, EMPLOYEE 참조
CREATE TABLE ARCHIVE (
    ARCHIVE_ID      INT          AUTO_INCREMENT,
    REPO_ID         INT          NOT NULL,
    WRITER_ID       INT          NOT NULL,
    ARCHIVE_TITLE   VARCHAR(200) NOT NULL,
    ARCHIVE_CONTENT TEXT         NOT NULL,
    CREATED_AT      DATETIME     NOT NULL DEFAULT NOW(),
    UPDATED_AT      DATETIME     NULL,
    CONSTRAINT PK_ARCHIVE         PRIMARY KEY (ARCHIVE_ID),
    CONSTRAINT FK_ARCHIVE_REPO    FOREIGN KEY (REPO_ID)
                                  REFERENCES  REPOSITORY(REPO_ID),
    CONSTRAINT FK_ARCHIVE_WRITER  FOREIGN KEY (WRITER_ID)
                                  REFERENCES  EMPLOYEE(EMPLOYEE_ID)
);

-- ⑨ ARCHIVE_FILE — ARCHIVE 참조
CREATE TABLE ARCHIVE_FILE (
    FILE_ID     INT          AUTO_INCREMENT,
    ARCHIVE_ID  INT          NOT NULL,
    FILE_NAME   VARCHAR(300) NOT NULL,
    FILE_PATH   VARCHAR(500) NOT NULL,
    FILE_SIZE   BIGINT       NOT NULL,
    UPLOADED_AT DATETIME     NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_ARCHIVE_FILE    PRIMARY KEY (FILE_ID),
    CONSTRAINT FK_ARCHIVEFILE_ARCHIVE FOREIGN KEY (ARCHIVE_ID)
                                      REFERENCES  ARCHIVE(ARCHIVE_ID)
);

-- ⑩ APPROVAL_FORM_TYPE — 다른 테이블이 참조하므로 먼저 생성
CREATE TABLE APPROVAL_FORM_TYPE (
    FORM_TYPE_ID        INT         AUTO_INCREMENT,
    FORM_TYPE_NAME      VARCHAR(50) NOT NULL,
    APPROVAL_STEP_COUNT INT         NOT NULL,   -- 1 또는 2
    CONSTRAINT PK_APPROVAL_FORM_TYPE PRIMARY KEY (FORM_TYPE_ID),
    CONSTRAINT UQ_FORM_TYPE_NAME     UNIQUE      (FORM_TYPE_NAME)
);

-- ⑪ APPROVAL — EMPLOYEE, APPROVAL_FORM_TYPE 참조
CREATE TABLE APPROVAL (
    APPROVAL_ID       INT          AUTO_INCREMENT,
    DRAFTER_ID        INT          NOT NULL,
    FORM_TYPE_ID      INT          NOT NULL,
    APPROVAL_TITLE    VARCHAR(200) NOT NULL,
    APPROVAL_CONTENT  TEXT         NOT NULL,
    LEAVE_START_DATE  DATE         NULL,
    LEAVE_END_DATE    DATE         NULL,
    AMOUNT            BIGINT       NULL,        -- 지출결의서 전용 (원 단위), 그 외 서식은 NULL
    APPROVAL_STATUS   VARCHAR(10)  NOT NULL DEFAULT 'PROGRESS',  -- PROGRESS/APPROVED/REJECTED
    CREATED_AT        DATETIME     NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_APPROVAL           PRIMARY KEY (APPROVAL_ID),
    CONSTRAINT FK_APPROVAL_DRAFTER   FOREIGN KEY (DRAFTER_ID)
                                     REFERENCES  EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT FK_APPROVAL_FORMTYPE  FOREIGN KEY (FORM_TYPE_ID)
                                     REFERENCES  APPROVAL_FORM_TYPE(FORM_TYPE_ID)
);

-- ⑫ APPROVAL_LINE — APPROVAL, EMPLOYEE 참조
CREATE TABLE APPROVAL_LINE (
    LINE_ID       INT          AUTO_INCREMENT,
    APPROVAL_ID   INT          NOT NULL,
    STEP_NO       INT          NOT NULL,
    APPROVER_ID   INT          NOT NULL,
    LINE_STATUS   VARCHAR(10)  NOT NULL DEFAULT 'WAIT',  -- WAIT/APPROVED/REJECTED
    LINE_COMMENT  VARCHAR(500) NULL,
    DECIDED_AT    DATETIME     NULL,
    CONSTRAINT PK_APPROVAL_LINE     PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_LINE_APPROVAL     FOREIGN KEY (APPROVAL_ID)
                                    REFERENCES  APPROVAL(APPROVAL_ID),
    CONSTRAINT FK_LINE_APPROVER     FOREIGN KEY (APPROVER_ID)
                                    REFERENCES  EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT UQ_LINE_APPROVAL_STEP UNIQUE     (APPROVAL_ID, STEP_NO)
);

-- ⑬ APPROVAL_REFERENCE — APPROVAL, DEPARTMENT, EMPLOYEE 참조
CREATE TABLE APPROVAL_REFERENCE (
    REF_ID       INT AUTO_INCREMENT,
    APPROVAL_ID  INT NOT NULL,
    DEPT_ID      INT NULL,
    EMPLOYEE_ID  INT NULL,
    CONSTRAINT PK_APPROVAL_REFERENCE PRIMARY KEY (REF_ID),
    CONSTRAINT FK_REF_APPROVAL       FOREIGN KEY (APPROVAL_ID)
                                     REFERENCES  APPROVAL(APPROVAL_ID),
    CONSTRAINT FK_REF_DEPT           FOREIGN KEY (DEPT_ID)
                                     REFERENCES  DEPARTMENT(DEPT_ID),
    CONSTRAINT FK_REF_EMPLOYEE       FOREIGN KEY (EMPLOYEE_ID)
                                     REFERENCES  EMPLOYEE(EMPLOYEE_ID),
    -- MySQL 8.0.16 미만에서는 무시됨 → 서비스 계층 검증 병행 필수
    CONSTRAINT CK_REF_ONE_TARGET     CHECK (
        (DEPT_ID IS NOT NULL AND EMPLOYEE_ID IS NULL) OR
        (DEPT_ID IS NULL AND EMPLOYEE_ID IS NOT NULL)
    )
);

-- ⑬-1 APPROVAL_FILE — APPROVAL 참조 (ARCHIVE_FILE과 동일 구조 - 지출결의서/프로젝트품의서 첨부용)
CREATE TABLE APPROVAL_FILE (
    FILE_ID     INT          AUTO_INCREMENT,
    APPROVAL_ID INT          NOT NULL,
    FILE_NAME   VARCHAR(300) NOT NULL,
    FILE_PATH   VARCHAR(500) NOT NULL,
    FILE_SIZE   BIGINT       NOT NULL,
    UPLOADED_AT DATETIME     NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_APPROVAL_FILE     PRIMARY KEY (FILE_ID),
    CONSTRAINT FK_APPROVALFILE_APPROVAL FOREIGN KEY (APPROVAL_ID)
                                    REFERENCES  APPROVAL(APPROVAL_ID)
);

-- ⑭ CHAT_ROOM — 다른 테이블이 참조하므로 먼저 생성
CREATE TABLE CHAT_ROOM (
    ROOM_ID    INT          AUTO_INCREMENT,
    ROOM_TYPE  VARCHAR(5)   NOT NULL,   -- DM / GROUP
    ROOM_NAME  VARCHAR(100) NULL,       -- GROUP만 값 존재
    CREATED_AT DATETIME     NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_CHAT_ROOM PRIMARY KEY (ROOM_ID)
);

-- ⑮ CHAT_MESSAGE — CHAT_ROOM, EMPLOYEE 참조 (CHAT_ROOM_MEMBER보다 먼저 생성)
CREATE TABLE CHAT_MESSAGE (
    MESSAGE_ID   INT           AUTO_INCREMENT,
    ROOM_ID      INT           NOT NULL,
    SENDER_ID    INT           NULL,        -- 시스템 메시지는 NULL
    MESSAGE_TYPE VARCHAR(10)   NOT NULL DEFAULT 'TEXT',  -- TEXT / FILE / SYSTEM
    CONTENT      VARCHAR(1000) NULL,
    SENT_AT      DATETIME      NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_CHAT_MESSAGE     PRIMARY KEY (MESSAGE_ID),
    CONSTRAINT FK_MESSAGE_ROOM     FOREIGN KEY (ROOM_ID)
                                   REFERENCES  CHAT_ROOM(ROOM_ID),
    CONSTRAINT FK_MESSAGE_SENDER   FOREIGN KEY (SENDER_ID)
                                   REFERENCES  EMPLOYEE(EMPLOYEE_ID)
);

-- ⑯ CHAT_ROOM_MEMBER — CHAT_ROOM, EMPLOYEE, CHAT_MESSAGE 참조
-- (CHAT_MESSAGE를 참조하는 LAST_READ_MESSAGE_ID는 두 테이블이 서로를
--  가리키는 순환 참조이므로, 테이블 생성 후 ALTER TABLE로 추가한다)
CREATE TABLE CHAT_ROOM_MEMBER (
    MEMBER_ROW_ID         INT      AUTO_INCREMENT,
    ROOM_ID               INT      NOT NULL,
    EMPLOYEE_ID            INT      NOT NULL,
    LAST_READ_MESSAGE_ID  INT      NULL,
    JOINED_AT             DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_CHAT_ROOM_MEMBER  PRIMARY KEY (MEMBER_ROW_ID),
    CONSTRAINT FK_ROOMMEMBER_ROOM   FOREIGN KEY (ROOM_ID)
                                    REFERENCES  CHAT_ROOM(ROOM_ID),
    CONSTRAINT FK_ROOMMEMBER_EMP    FOREIGN KEY (EMPLOYEE_ID)
                                    REFERENCES  EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT UQ_ROOMMEMBER_ROOM_EMP UNIQUE    (ROOM_ID, EMPLOYEE_ID)
);

ALTER TABLE CHAT_ROOM_MEMBER
    ADD CONSTRAINT FK_ROOMMEMBER_LASTREAD FOREIGN KEY (LAST_READ_MESSAGE_ID)
        REFERENCES CHAT_MESSAGE(MESSAGE_ID);

-- ⑰ CHAT_ATTACHMENT — CHAT_MESSAGE 참조
CREATE TABLE CHAT_ATTACHMENT (
    ATTACH_ID  INT          AUTO_INCREMENT,
    MESSAGE_ID INT          NOT NULL,
    FILE_NAME  VARCHAR(300) NOT NULL,
    FILE_PATH  VARCHAR(500) NOT NULL,
    FILE_SIZE  BIGINT       NOT NULL,
    CONSTRAINT PK_CHAT_ATTACHMENT   PRIMARY KEY (ATTACH_ID),
    CONSTRAINT FK_CHATATTACH_MESSAGE FOREIGN KEY (MESSAGE_ID)
                                     REFERENCES  CHAT_MESSAGE(MESSAGE_ID),
    CONSTRAINT UQ_CHATATTACH_MESSAGE UNIQUE      (MESSAGE_ID)
);


-- CHAT_ROOM_MEMBER_SUSPENSION - 정지될때
CREATE TABLE CHAT_ROOM_MEMBER_SUSPENSION (
    SUSPENSION_ID INT NOT NULL AUTO_INCREMENT,
    ROOM_ID INT NOT NULL,
    EMPLOYEE_ID INT NOT NULL,
    HIDDEN_FROM_MESSAGE_ID INT NOT NULL,
    HIDDEN_TO_MESSAGE_ID INT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (SUSPENSION_ID),

    INDEX IDX_CHAT_MEMBER_SUSPENSION_LOOKUP (
        ROOM_ID,
        EMPLOYEE_ID,
        HIDDEN_FROM_MESSAGE_ID,
        HIDDEN_TO_MESSAGE_ID
    ),

    CONSTRAINT FK_CHAT_MEMBER_SUSPENSION_ROOM
        FOREIGN KEY (ROOM_ID)
        REFERENCES CHAT_ROOM (ROOM_ID),

    CONSTRAINT FK_CHAT_MEMBER_SUSPENSION_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE (EMPLOYEE_ID)
);




ALTER TABLE CALENDAR_EVENT
    ADD COLUMN DEPT_ID INT NULL,
    ADD CONSTRAINT FK_EVENT_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID);

-- ⑱ EMPLOYEE.BIRTH_DATE — 메인 대시보드 "이번 달 생일자" 표기 기능 추가.
-- 계정 생성 시에는 입력하지 않고(관리자 등록 화면에 입력란 없음), 본인이 마이페이지에서
-- 직접 입력/수정한다. 그래서 NULL 허용 - 기존 계정과 새로 만든 계정 모두 처음엔 값이 없다.
ALTER TABLE EMPLOYEE
    ADD COLUMN BIRTH_DATE DATE NULL AFTER HIRE_DATE;

-- CALENDAR_EVENT COLUMN IS_HOLIDAY - notice의 pin기능과 유사
-- CALENDAR_EVENT에 공휴일 체크박스 값을 저장할 컬럼
ALTER TABLE CALENDAR_EVENT
    ADD COLUMN IS_HOLIDAY TINYINT(1) NOT NULL DEFAULT 0;
